# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MarFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('size', models.IntegerField()),
                ('hash', models.CharField(max_length=128)),
                ('hash_function', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PartialLanguageUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('mar_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.MarFile', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartialUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mar_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.MarFile', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.CharField(db_index=True, max_length=50)),
                ('os', models.CharField(db_index=True, max_length=50)),
                ('added', models.DateTimeField(auto_now=True, db_index=True)),
                ('see_also', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_partial_updates', models.IntegerField(default=1)),
                ('current_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='release.Release')),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.UpdateChannel'),
        ),
        migrations.AddField(
            model_name='release',
            name='release_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.MarFile', unique=True),
        ),
        migrations.AddField(
            model_name='partialupdate',
            name='new_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_updates', to='release.Release'),
        ),
        migrations.AddField(
            model_name='partialupdate',
            name='old_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patial_update_dests', to='release.Release'),
        ),
        migrations.AddField(
            model_name='partiallanguageupdate',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.PartialUpdate', unique=True),
        ),
        migrations.AddField(
            model_name='languagefile',
            name='mar_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.MarFile', unique=True),
        ),
        migrations.AddField(
            model_name='languagefile',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.Release'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set([('name', 'channel', 'product', 'os')]),
        ),
    ]
