# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marfile',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
